version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: ${PROJECT_NAME}_nginx
    ports:
      - ${WEB_PORT}:8000
    volumes:
      - .:/app
      - ./etc/nginx:/etc/nginx/conf.d
    depends_on:
      - web

  db:
    image: mysql
    container_name: ${PROJECT_NAME}_mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: adminadmin
      MYSQL_DATABASE: django
    volumes:
      - ./db:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ${PROJECT_NAME}_phpmyadmin
    environment:
      - PMA_ARBITRARY=1
    restart: always
    ports:
      - ${WEB_PHPMYADMIN}:80
    volumes:
      - /sessions

  web:
    build: .
    container_name: ${PROJECT_NAME}_server_backend
    volumes:
      - .:/app
    expose:
      - "8000"
    depends_on:
      - db